// dsh-notifier strings.mjs
// 自动推送文案表：lang: 'zh'（默认）| 'en'。未知值一律回落 zh（安全配置的
// 非法值不配得到宽松解释，与 redaction 归一化同法）。
// 只覆盖插件自家文案（headline / 自有 detail / 状态正文模板）；助手摘录等
// 宿主数据片段不属于翻译范围（它们本就是会话语言）。

/** zh：与既有硬编码文案逐字节一致（默认路径零行为变化）。 */
const ZH = {
  turnStart: '🚀 任务开始',
  turnEndHeadline: {
    completed: '✅ 任务完成',
    error: '❌ 任务出错',
    blocked: '🚫 任务被阻塞',
    aborted: '⏹ 任务已中止',
    'max-tokens': '⚠️ 达到 Token 上限',
    interrupted: '⏸ 任务异常中断',
  },
  turnEndDetail: {
    error: '任务执行出错',
    blocked: '任务被阻塞，等待你处理',
    'max-tokens': '某一步骤达到输出 Token 上限',
    interrupted: '会话被异常中断，等待恢复',
  },
  approval: {
    // event-listener 侧（approval/asked 自动推送）
    headline: '🔐 需要你批准',
    toolName: (name) => `工具 ${name}`,
    toolFallback: '一个操作',
    reasonPrefix: '：',
    detail: (tool, reason) => `${tool} 需要授权${reason}`,
    // approval/router.mjs 侧（审批卡片与裁决回执）
    cardTitle: (toolName) => `需要批准：${toolName}`,
    reasonFallback: 'agent 请求执行一个需要授权的操作',
    content: (reason) => `${reason}\n\n批准将仅对本次调用生效（token 单次核销）。`,
    fallbackText: (title, content) => `${title}\n${content}\n\n回复 1 批准 / 2 拒绝`,
    sentButtonNote: (names) => `${names.join('、')} 已发可点按钮`,
    sentNoticeNote: (names) => `${names.join('、')} 已发审批通知`,
    broadcastWithNotes: (notes) => `（${notes.join('；')}；无按钮渠道可回复 1 批准 / 2 拒绝）`,
    broadcastNoButtons: '（本渠道无按钮：回复 1 批准 / 2 拒绝）',
    alreadyResolved: '该审批已被处理或已失效，此次点击无效',
    noDeliveryRecord: '未找到该审批的投递记录，无法核验回复来源，请回桌面处理',
    receiverOnly: '仅审批接收人可点击裁决',
    missingAccountCallback: '审批回调缺少账号来源，无法裁决（请升级客户端）',
    controlNotWired: 'Control Core 未接线，审批不可用',
    notForYou: '此审批不是发给你的(无权裁决)',
    missingAccountReply: '审批回复缺少账号来源，无法裁决',
    alreadyDecidedRace: '该审批已被处理（首达采纳，此次回复无效）',
    terminatedCard: '⏹ 已终止：agent 会话已结束，审批取消',
    parallelTimeout: '⏱ 手机端等待结束：请到桌面处理（按钮已失效）',
    timeoutResolved: '⏱ 超时未响应：已交还桌面处理（按钮失效）',
    remoteApproved: '✅ 已远程批准（本次）',
    remoteRejected: '❌ 已远程拒绝',
    desktopHandled: '🖥️ 已在桌面处理（手机按钮已失效）',
    escStillWaiting: (toolName) => `${toolName ?? '操作'} 仍在等待批准`,
    escNoteFallback: '仍在等待批准',
    escStageNote1: '第 1 次升级提醒',
    escStageNote2: '第 2 次升级提醒',
    staleNotice: '该审批因宿主重启已失效，请回桌面处理',
    escContent: (note, waitedSeconds, cardChannels) => `${note}（已等待 ${waitedSeconds}s）。\n回复 1 批准 / 2 拒绝${cardChannels !== '' ? `，或点击 ${cardChannels} 卡片按钮` : ''}。`,
  },
  // 身份命令回执（inbound/commands.mjs /pair /whoami /unpair）
  commands: {
    channelNames: { telegram: 'Telegram', feishu: '飞书', qq: 'QQ', wxpusher: 'WxPusher', wechat: '微信', dingtalk: '钉钉' },
    unknownChannel: '未知渠道',
    whoamiHead: (channelName, userId) => `你的${channelName}身份：${userId}`,
    whoamiUnbound: (head) => `${head}\n尚未绑定。发送 /pair <配对码> 完成绑定；配对码请联系管理员，或查看本机引导码文件。`,
    labelSuffix: (label) => `（${label}）`,
    whoamiBound: (head, label, role) => `${head}\n已绑定${label}，角色：${role}。/help 查看会话命令。`,
    guidedHelp: `引导模式：白名单为空，仅注册命令可用。
  /pair <配对码> [备注] — 绑定你的身份（首位绑定者成为 owner）
  /whoami — 查看你的渠道身份
配对码位置：本机引导码文件或管理台「成员」页。其余消息在完成绑定前不受理。`,
    memberHelp: `身份命令：
  /whoami — 查看你的绑定身份
  /unpair — 解绑当前身份（换号时用，之后重新 /pair）
会话命令见 /help（由会话路由应答）。`,
    pairUsage: '用法：/pair <配对码> [备注]\n配对码由管理员在管理台生成（10 分钟内有效）；首次部署的引导码见本机引导码文件。',
    pairNotInGroup: '配对码请勿在群聊中发送（会被其他人抢用）。请私聊我发送 /pair <配对码>。',
    alreadyBound: '你已绑定过身份（/whoami 查看）。如需换号，先发送 /unpair。',
    pairExpiredBootstrapPending: '配对码已过期。当前已有在铸引导码，请管理员查看本机引导码文件或管理台获取新码后重试。',
    pairExpiredReminted: '配对码已过期。已重铸一枚引导码，请管理员查看本机引导码文件或管理台获取新码后重试。',
    pairExpiredRemintFailed: '配对码已过期。引导码重铸失败或节流中，请稍后再试或使用管理台铸码。',
    reasonInvalidCode: '配对码无效（核对后重试；连续错 5 次将临时锁定）。',
    reasonLockedOut: '尝试次数过多，已临时锁定 10 分钟。',
    reasonExpired: '配对码已过期，请联系管理员重新生成。',
    reasonRevoked: '配对码已被撤销，请联系管理员重新生成。',
    reasonLocked: '配对码已被锁定，请联系管理员。',
    reasonAlreadyRedeemed: '配对码已被使用（单次有效），请联系管理员重新生成。',
    pairFailed: (reason) => `配对失败：${reason}`,
    bindWriteFailed: (reason) => `配对码核销成功，但绑定写入失败（${reason}）。请联系管理员检查状态文件。`,
    pairSuccessOwner: (help) => `配对成功！你是首位成员（owner），已可使用全部功能。\n${help}`,
    pairSuccess: (label, help) => `配对成功！你的身份已绑定${label !== '' ? `（${label}）` : ''}。\n${help}`,
    unpairNotBound: '你尚未绑定身份，无需解绑。',
    unpairLastOwner: '你是唯一的 owner，不能自解绑（否则实例将无人可管理）。请先在管理台添加成员或转移角色，再解绑旧号。',
    unpairFailed: (reason) => `解绑失败：${reason}`,
    unpaired: '已解绑。换新号后重新发送 /pair <配对码> 即可。',
    internalError: '命令内部错误，请稍后重试；若持续失败请联系管理员查看宿主日志。',
  },
  // 动作回执（actions.mjs，通知按钮点击回执）
  actions: {
    executed: '✅ 已执行',
    alreadyHandledOrExpired: '该操作已处理或已过期',
    invalidAction: '无效操作',
    expiredNoVault: '该操作已失效',
    alreadyHandledToken: '该操作已处理或已过期（token 单次核销）',
    expired: '该操作已过期',
    alreadyHandled: '该操作已处理',
    useOriginalChat: '请到原会话操作',
    unknownKind: '未知操作类型',
    notEffective: '操作未生效',
    handlerErrorReceipt: '动作已核销，但执行异常（任务状态请以 /agent 为准）',
    dispatchError: '处理异常，请重试',
  },
  agentError: {
    headline: '❌ Agent 执行出错',
    detailFallback: 'agent 执行出错',
  },
  status: {
    longRunningHeadline: '⏱ 任务进行中',
    stallHeadline: '⚠️ 疑似卡住',
    runtimeLine: (elapsed, idle) => `已运行 ${elapsed}，最近活动 ${idle} 前`,
    stallHint: '长工具执行可能误报；可回复 /stop 取消，或调大 events.stall.afterMs',
    stopHint: '回复 /stop 取消',
    stopActionLabel: '⏹ 停止任务',
    recentOutputPrefix: '最近输出：',
  },
  // 入站回执（index.mjs /stop 与 questions 桥兜底）
  stop: {
    invalidSession: '无效会话',
    queryFailed: '会话查询失败',
    notFound: '会话不存在（任务可能已结束）',
    stopped: '✅ 已停止任务',
    cancelFailed: '取消失败（agent 可能已空闲）',
  },
  index: {
    questionsNotReady: '提问服务未就绪',
  },
  // 远程提问桥（questions/router.mjs）——提问卡片、编号回复、裁决回执、升级提醒
  questions: {
    cardTitle: (text) => `提问：${text}`,
    noContextPrompt: 'agent 需要你做一个选择',
    multiSelectTag: '（多选）',
    singleSelectTag: '（单选）',
    replyNumberHint: '回复编号',
    replyNumberHintMulti: '回复编号（多选逗号分隔，如 1,3）',
    replyNumberSuffix: (how) => `（${how}）`,
    answeredOrExpired: '该提问已回答或已过期',
    alreadyAnsweredFirstWin: '该提问已被作答（首达采纳）',
    rejectedExpiredOrInvalid: (expired) => `作答被拒绝（${expired ? '已过期' : '校验失败'}）`,
    rejectedMismatch: '作答被拒绝（问题不匹配）',
    goOriginalChat: '请到原会话操作',
    customAnswerHint: '✍️ 自定义回答：直接回复「答：<你的回答>」',
    skippedFeedback: '⏭ 已跳过该提问：交还桌面处理',
    invalidOption: '无效选项（只接受提问时给出的编号）',
    answeredWithLabels: (labels) => `✅ 已作答：${labels.join('、')}`,
    answerTooLong: (max) => `回答过长（超过 ${max} 字符），已拒绝；请精简后重发或在桌面端直接回答`,
    answeredCustom: (text) => `✅ 已作答（自定义）：${text}`,
    emptyCustomAnswer: '请在「答：」后面写回答',
    noChatContextHint: '该回复未能定位到提问卡片（缺少会话上下文），请回到原卡片回复或使用管理台裁决',
    notAuthorizedToAnswer: '此提问不是你作答的（无权回答）',
    singleOnlyHint: '本题是单选，请只回复一个编号',
    outOfRangeHint: (max, multi) => `编号需在 1-${max} 之间${multi ? '，多选用逗号分隔（如 1,3）' : ''}`,
    wrongNumberEcho: (why, hint) => `❓ ${why}\n${hint}`,
    escalationText: (question, note, waited) => `提问仍在等待作答：${question}\n${note}（已等待 ${waited}s）。请点击选项卡片按钮作答；无卡片渠道可回复选项编号。`,
    escalationWaitingFallback: '仍在等待作答',
    escStageNote1: '提问仍在等待作答',
    escStageNote2: '提问仍在等待作答（第 2 次提醒）',
    terminatedText: '⏹ 已终止：agent 会话已结束，提问取消',
    skippedResolvedText: '⏭ 已跳过：交还桌面处理',
    timeoutResolvedText: '⏱ 超时未作答：已交还桌面（按钮失效）',
    answeredWithLabelsVia: (labels, via) => `✅ 已作答：${labels.join('、')}（来源 ${via}）`,
  },
  // 裁决失败话术（inbound/verdict-text.mjs）——按钮/回执失败按原因分层
  verdict: {
    nounApproval: '该审批',
    nounQuestion: '该提问',
    tokenRequired: '本次操作缺少有效凭证，请回到发起操作的会话重新点击',
    keyMismatch: '操作与目标不匹配，请回到原卡片操作',
    sourceChatMismatch: '请到原会话操作',
    alreadyResolved: (noun) => `${noun}已处理，无需重复操作`,
    expired: (noun) => `${noun}已过期，请重新发起`,
    invalidDecision: '无效的操作类型',
    notFound: (noun) => `${noun}已处理或已过期`,
    cardMissing: '原消息可能已被删除，无法在此展示结果；操作结果以台账为准',
  },
  // 命令族与远程对话回执（inbound/conversation.mjs）
  conversation: {
    helpLines: [
      '命令集：',
      '  /status — 查看绑定与 agent 状态',
      '  /agent — 活跃会话分组视图（workspace | sid | 状态 | 出站通道 | quiet）',
      '  /agent use <workspace|sid 前缀> — 本对话切到该会话（智能绑定）',
      '  /agent back — 解除本对话绑定，回通道默认',
      '  /tasks — 活跃任务列表（taskRef | workspace | 状态 | 待关注）',
      '  /use <workspace|sid 前缀> — 选择任务（等价 /agent use；歧义选择卡时投递原消息）',
      '  /bind <sessionId> — 绑定到指定会话（sid 级精确操作）',
      '  /unbind — 解绑（回到通道默认路由：通道默认 agent，未配置则最近活跃）',
      '  /stop — 取消当前 turn',
      '  /route — 查看当前双向解析（会话→通道 / 通道→会话）',
      '  /quiet <workspace|sid> — 静默该会话的出站推送（远程对话不受影响）',
      '  /unquiet <workspace|sid> — 恢复该会话的出站推送',
      '  /help — 本帮助',
      '',
      '直接发文本 = 对话；! 前缀 = 纠偏（steer）；.. 结尾 = 立即发送（合并窗内）。',
      '长任务自动心跳（默认 15min 起）与疑似卡住提醒（默认 10min 无事件）；卡片通道可点按钮停止，其余 /stop。',
    ],
    statusBindLabel: '绑定：',
    bindUnset: '（未显式绑定：走通道默认路由）',
    statusTargetLabel: '目标：',
    targetUnset: '（无活跃会话，先 /bind 或等 agent 启动）',
    statusStateLabel: '状态：',
    statusNotFound: '未找到',
    activeSessionsLabel: '活跃会话：',
    activeSessionsNone: '（无）',
    bindUsage: '用法：/bind <sessionId>（可先用 /status 查看活跃会话）',
    bindMissingSession: (target) => `会话 ${target} 不存在（用 /status 查看活跃会话）`,
    boundReceipt: (target) => `已绑定 ${target}`,
    unboundReceipt: '已解绑（回到通道默认路由）',
    stopNone: '当前没有可停止的会话',
    stopRequested: (sid) => `已请求取消 ${sid} 的当前 turn`,
    stopFailed: '取消失败（agent 可能已空闲）',
    agentUsage: '用法：/agent（活跃会话列表）| /agent use <workspace|sid 前缀> | /agent back',
    routeUnavailable: '路由引擎未装配（v0.3.2 router 缺失）：/route 暂不可用；/status 仍可查看会话与绑定。',
    quietUnavailable: '路由引擎未装配（v0.3.2 router 缺失）：/quiet 暂不可用；/status 仍可查看会话与绑定。',
    quietUsage: (cmd) => `用法：/${cmd} <workspace 名 | sessionId | sid 前缀（≥4 位）>`,
    quietWriteFailed: (cmd) => `/${cmd} 写入失败（路由状态存储不可用），请稍后再试`,
    quietMarkMuted: '🔇 已静默',
    quietMarkResumed: '🔔 已恢复',
    quietReceipt: (mark, label, sid, matchedBy) => `${mark} ${label} / ${sid}（${matchedBy}）的出站推送`,
    quietHint: '（远程审批与对话不受影响；/unquiet <workspace|sid> 恢复）',
    unknownWorkspace: '(未知 workspace)',
    unknownCommand: (cmd) => `未识别的命令 /${cmd}（用 /help 查看命令集）`,
    agentListUnavailable: '路由引擎未装配（v0.3.2 router 缺失）：/agent 列表暂不可用；/status 仍可查看会话与绑定。',
    agentListHeader: '活跃会话分组视图（workspace | sid | 状态 | 出站通道 | quiet）：',
    agentListDegraded: '（会话台账 registry 未装配：按宿主 agent 列表降级展示，活跃排序不可用）',
    agentListEmpty: '  （无活跃会话：先在宿主开一个会话，或 /bind <sessionId>）',
    statusUnknown: '未知',
    outboundUnavailable: '(解析不可用)',
    agentListFooter: '（/agent use <workspace|sid 前缀> 切换；/agent back 回通道默认；/route 查看双向解析）',
    matchedByWorkspace: (needle) => `workspace=${needle}`,
    matchedBySessionId: 'sessionId 精确匹配',
    matchedBySidPrefix: 'sid 前缀唯一命中',
    prefixAmbiguous: (needle, count) => `前缀 ${needle} 命中 ${count} 个活跃会话，请精确指定：`,
    prefixHint: '（或用 workspace 名精确匹配）',
    noMatch: (needle) => `未匹配到会话 ${needle}（用 /agent 查看活跃会话；sid 前缀匹配需至少 4 位）`,
    agentUseUsage: '用法：/agent use <workspace 名 | sessionId | sid 前缀（≥4 位）>',
    agentUseBound: (workspace, sid, matchedBy) => `已绑定 ${workspace} / ${sid}（${matchedBy}；/agent back 回通道默认）`,
    agentBackBound: (sid) => `已回到通道默认（解除与 ${sid} 的绑定）`,
    agentBackUnbound: '当前没有显式绑定（本就走通道默认路由）',
    routeOutboundHeader: '【出站】当前会话 → 通道（逐层解析）',
    routeNoTarget: '  当前无目标会话（无绑定且无活跃会话可兜底）',
    routeInboundHeader: '【入站】本通道 → 会话（当前解析）',
    routeSourceLine: (label) => `  来源：${label}`,
    routeTargetLine: (sid) => `  目标：${sid ?? '（无）'}`,
    routeAmbiguousLine: (ambiguous) => `  歧义：${ambiguous ? '是（多活跃会话，已按最近活跃投递）' : '否'}`,
    routeCandidatesLine: (joined) => `  候选：${joined}`,
    routeChannelDefaultLine: (channel, value) => `  通道默认 agent（${channel}）：${value ?? '未配置'}`,
    noActiveSession: '没有活跃会话可投递（用 /bind <sessionId> 绑定，或 /status 查看）',
    sessionGone: (sid) => `会话 ${sid} 不存在或已退出（用 /status 查看）`,
    deliverFailed: '投递失败（详见宿主日志）',
    deliveredAmbiguous: (sid, count) => `已投 ${sid}（该 workspace 有 ${count} 个活跃会话，用 /agent use 或 /bind 精确指定）`,
    groupControlDenied: '群聊不允许远程控制，请回原私聊会话操作',
    controlSourceUnverified: '远程控制来源无法确认，请回原私聊会话操作',
    conversationDisabled: '远程对话默认关闭，请在 session policy 中显式开启',
    notPaired: '请先完成配对后再操作',
    controlRejected: '远程控制被拒绝，请回桌面确认',
    joiner: '、',
    // /route 入站段来源层标签（与 agent-router source 值一一对应）
    inboundSourceLabels: {
      bind: '显式绑定（/bind 或 /agent use）',
      'channel-default': '通道默认 agent',
      'single-agent': '唯一 agent 兜底',
      latest: '最近活跃（默认兜底）',
    },
  },
  // 晨报（ledger.mjs composeDigest + index.mjs 标题）
  digest: {
    title: '📊 通知摘要',
    windowLine: (from, to, total) => `时间窗：${from} ~ ${to}，共 ${total} 条通知`,
    completed: (n) => `✅完成 x${n}`,
    error: (n) => `❌出错 x${n}`,
    agentError: (n) => `❌agent出错 x${n}`,
    blocked: (n) => `🚫阻塞 x${n}`,
    aborted: (n) => `⏹中止 x${n}`,
    maxTokens: (n) => `⚠️token上限 x${n}`,
    interrupted: (n) => `⏸中断 x${n}`,
    approval: (n) => `🔐审批 x${n}`,
    other: (n) => `其他 x${n}`,
    joiner: '、',
    failedLine: (n) => `另有 ${n} 条渠道投递失败（详见日志）`,
    empty: (from, to) => `时间窗：${from} ~ ${to}，无通知记录`,
  },

  // 白名单拒绝回执 + decide 来源校验话术（inbound/bus.mjs）
  bus: {
    identityLine: (channelName, userId) => `你的${channelName}身份是 ${userId}。`,
    guidedReply: (idLine) => `${idLine}\n当前为引导模式（白名单为空）。发送 /pair <配对码> 完成绑定（首位绑定者成为 owner），配对码见宿主启动日志；/whoami 查看你的身份。`,
    whitelistReply: (idLine) => `${idLine}\n你不在白名单中。请联系管理员生成配对码，然后发送 /pair <配对码> 绑定。`,
  },

  // 渠道适配器回执（telegram-bot.mjs）
  telegram: {
    terminalFallbackSuffix: '（按钮失效）',
    truncateMark: '…（内容过长，已截断）',
    refExpired: '该操作已处理或已过期（按钮单次有效）',
    sourceNote: (user) => `（来源：telegram user ${user}）`,
    answeredShort: '✅ 已作答',
    approvedOnce: '✅ 已批准（单次有效）',
    rejected: '❌ 已拒绝',
    approveButton: '✅ 批准（本次）',
    rejectButton: '❌ 拒绝',
    customAnswerButton: '✍️ 自定义回答',
    skipButton: '⏭ 跳过',
    editFallbackNote: '（操作已完成；原消息可能已删除）',
  },
  // 渠道适配器回执（feishu-bot.mjs）
  feishu: {
    approveButton: '✅ 批准（本次）',
    rejectButton: '❌ 拒绝',
    approvalResolvedTitle: '审批已完成',
    actionResolvedTitle: '操作已完成',
    questionResolvedTitle: '提问已作答',
    unsupportedMessageType: '暂不支持该消息类型',
    cardExpiredToast: '该操作已处理或已过期（请回桌面处理）',
    unknownAction: '未知操作',
    answeredShort: '✅ 已作答',
    approvedOnce: '✅ 已批准（单次有效）',
    rejected: '❌ 已拒绝',
    sourceNote: (user) => `（来源：飞书用户 ${user}）`,
    groupDowngradeNote: '（群聊通道降级为纯文本，请到私聊操作）',
    cardPatchFailedNote: '（原卡片已不可编辑，此为准结果）',
  },
  // QQ 网关卡片/按钮回执（qq-gw.mjs）
  qq: {
    approveLabel: '✅ 批准',
    approveVisited: '已批准',
    rejectLabel: '❌ 拒绝',
    rejectVisited: '已拒绝',
    selectedVisited: '已选择',
    markdownFooter: (isUserTarget) => `点击按钮完成裁决${isUserTarget ? '（仅你本人可点）' : ''}：`,
    customAnswerLabel: '✍️ 自定义回答',
    resultLine: (text) => `[审批结果] ${text}`,
  },
  // 钉钉审批文本回执（dingtalk-stream.mjs）
  dingtalk: { resultLine: (text) => `[审批结果] ${text}` },
  // WxPusher 审批文本回执（wxpusher-callback.mjs）
  wxpusher: { resultLine: (text) => `[审批结果] ${text}` },

  // 渠道自检（health.mjs / notify_test 工具推送）
  health: {
    title: 'dsh-notifier 自检',
    testMessage: 'dsh-notifier 渠道自检：这是一条测试消息，收到即说明该渠道配置正确。',
  },
}

/** en：与 zh 同形状。 */
const EN = {
  turnStart: '🚀 Task started',
  turnEndHeadline: {
    completed: '✅ Task complete',
    error: '❌ Task failed',
    blocked: '🚫 Task blocked',
    aborted: '⏹ Task aborted',
    'max-tokens': '⚠️ Output token limit reached',
    interrupted: '⏸ Task interrupted',
  },
  turnEndDetail: {
    error: 'task execution failed',
    blocked: 'Task blocked, waiting for you',
    'max-tokens': 'A step hit its output token cap',
    interrupted: 'Session was interrupted abnormally, awaiting recovery',
  },
  approval: {
    // event-listener 侧（approval/asked 自动推送）
    headline: '🔐 Approval needed',
    toolName: (name) => `Tool ${name}`,
    toolFallback: 'An operation',
    reasonPrefix: ': ',
    detail: (tool, reason) => `${tool} needs your approval${reason}`,
    // approval/router.mjs 侧（approval cards and decision receipts）
    cardTitle: (toolName) => `Approval needed: ${toolName}`,
    reasonFallback: 'agent requested an operation that requires authorization',
    content: (reason) => `${reason}\n\nApproval applies to this call only (single-use token).`,
    fallbackText: (title, content) => `${title}\n${content}\n\nReply 1 approve / 2 reject`,
    sentButtonNote: (names) => `${names.join(', ')} got tappable buttons`,
    sentNoticeNote: (names) => `${names.join(', ')} got the approval notice`,
    broadcastWithNotes: (notes) => `(${notes.join('; ')}; channels without buttons can reply 1 approve / 2 reject)`,
    broadcastNoButtons: '(no buttons on this channel: reply 1 approve / 2 reject)',
    alreadyResolved: 'This approval was already handled or has expired; this click is void',
    noDeliveryRecord: 'No delivery record found for this approval; cannot verify the replier. Please handle it on desktop.',
    receiverOnly: 'Only the approval recipients may decide by tap',
    missingAccountCallback: 'Approval callback is missing its account source; cannot decide (please upgrade the client)',
    controlNotWired: 'Control Core not wired; approval unavailable',
    notForYou: 'This approval was not sent to you (not authorized to decide)',
    missingAccountReply: 'Approval reply is missing its account source; cannot decide',
    alreadyDecidedRace: 'This approval was already decided (first decision wins; this reply is void)',
    terminatedCard: '⏹ Terminated: agent session ended, approval cancelled',
    parallelTimeout: '⏱ Phone wait ended: please handle on desktop (buttons invalidated)',
    timeoutResolved: '⏱ Timed out with no response: handed back to desktop (buttons invalidated)',
    remoteApproved: '✅ Approved remotely (this call)',
    remoteRejected: '❌ Rejected remotely',
    desktopHandled: '🖥️ Handled on desktop (phone buttons invalidated)',
    escStillWaiting: (toolName) => `${toolName ?? 'Operation'} is still awaiting approval`,
    escNoteFallback: 'still awaiting approval',
    escStageNote1: 'Escalation reminder 1',
    escStageNote2: 'Escalation reminder 2',
    staleNotice: 'This approval was invalidated by a host restart; please handle it on desktop',
    escContent: (note, waitedSeconds, cardChannels) => `${note} (waited ${waitedSeconds}s).\nReply 1 approve / 2 reject${cardChannels !== '' ? `, or tap the ${cardChannels} card buttons` : ''}.`,
  },
  // 身份命令回执（inbound/commands.mjs /pair /whoami /unpair）
  commands: {
    channelNames: { telegram: 'Telegram', feishu: 'Feishu', qq: 'QQ Bot', wxpusher: 'WxPusher', wechat: 'WeChat iLink', dingtalk: 'DingTalk' },
    unknownChannel: 'Unknown channel',
    whoamiHead: (channelName, userId) => `Your ${channelName} identity: ${userId}`,
    whoamiUnbound: (head) => `${head}\nNot bound yet. Send /pair <pairing code> to bind; ask an admin for a pairing code, or check the local bootstrap code file.`,
    labelSuffix: (label) => ` (${label})`,
    whoamiBound: (head, label, role) => `${head}\nBound${label}, role: ${role}. See /help for session commands.`,
    guidedHelp: `Guided mode: the whitelist is empty; only registration commands are available.
  /pair <pairing code> [note] — bind your identity (the first binder becomes owner)
  /whoami — show your channel identity
Pairing code location: the local bootstrap code file or the admin console "Members" page. Other messages are not accepted until binding is complete.`,
    memberHelp: `Identity commands:
  /whoami — show your bound identity
  /unpair — unbind the current identity (use when switching accounts, then /pair again)
Session commands: see /help (answered by the session router).`,
    pairUsage: 'Usage: /pair <pairing code> [note]\nThe pairing code is generated by an admin in the admin console (valid for 10 minutes); for first deployment see the local bootstrap code file.',
    pairNotInGroup: 'Do not send pairing codes in group chats (others may grab it). DM me /pair <pairing code> instead.',
    alreadyBound: 'You are already bound (see /whoami). To switch accounts, send /unpair first.',
    pairExpiredBootstrapPending: 'The pairing code has expired. A bootstrap code is currently being minted; ask the admin to fetch the new code from the local bootstrap code file or the admin console and retry.',
    pairExpiredReminted: 'The pairing code has expired. A new bootstrap code has been minted; ask the admin to fetch it from the local bootstrap code file or the admin console and retry.',
    pairExpiredRemintFailed: 'The pairing code has expired. Bootstrap remint failed or is throttled; try again later or mint a code in the admin console.',
    reasonInvalidCode: 'Invalid pairing code (check and retry; 5 consecutive failures trigger a temporary lockout).',
    reasonLockedOut: 'Too many attempts; temporarily locked for 10 minutes.',
    reasonExpired: 'The pairing code has expired; ask an admin to regenerate it.',
    reasonRevoked: 'The pairing code has been revoked; ask an admin to regenerate it.',
    reasonLocked: 'The pairing code has been locked; contact an admin.',
    reasonAlreadyRedeemed: 'The pairing code has already been used (single-use); ask an admin to regenerate it.',
    pairFailed: (reason) => `Pairing failed: ${reason}`,
    bindWriteFailed: (reason) => `Pairing code redeemed, but the binding write failed (${reason}). Ask an admin to check the state file.`,
    pairSuccessOwner: (help) => `Paired! You are the first member (owner) with full access.\n${help}`,
    pairSuccess: (label, help) => `Paired! Your identity is bound${label !== '' ? ` (${label})` : ''}.\n${help}`,
    unpairNotBound: 'You are not bound; nothing to unbind.',
    unpairLastOwner: 'You are the only owner and cannot unbind yourself (the instance would be left unmanageable). Add a member or transfer the role in the admin console first, then unbind the old account.',
    unpairFailed: (reason) => `Unbind failed: ${reason}`,
    unpaired: 'Unbound. After switching to a new account, send /pair <pairing code> again.',
    internalError: 'Internal command error, please retry; if it persists, ask an admin to check the host logs.',
  },
  // 动作回执（actions.mjs，通知按钮点击回执）
  actions: {
    executed: '✅ Executed',
    alreadyHandledOrExpired: 'This action was already handled or has expired',
    invalidAction: 'Invalid action',
    expiredNoVault: 'This action has expired',
    alreadyHandledToken: 'This action was already handled or has expired (token is single-use)',
    expired: 'This action has expired',
    alreadyHandled: 'This action was already handled',
    useOriginalChat: 'Please operate in the original chat',
    unknownKind: 'Unknown action type',
    notEffective: 'Action had no effect',
    handlerErrorReceipt: 'Action token consumed, but execution failed (check task state via /agent)',
    dispatchError: 'Processing error, please retry',
  },
  agentError: {
    headline: '❌ Agent error',
    detailFallback: 'agent execution failed',
  },
  status: {
    longRunningHeadline: '⏱ Task still running',
    stallHeadline: '⚠️ Possibly stalled',
    runtimeLine: (elapsed, idle) => `Running ${elapsed}, last activity ${idle} ago`,
    stallHint: 'Long tool call may be a false alarm; reply /stop to cancel, or raise events.stall.afterMs',
    stopHint: 'Reply /stop to cancel',
    stopActionLabel: '⏹ Stop task',
    recentOutputPrefix: 'Recent output: ',
  },
  // 入站回执（index.mjs /stop 与 questions 桥兜底）
  stop: {
    invalidSession: 'Invalid session',
    queryFailed: 'Session lookup failed',
    notFound: 'Session not found (task may have ended)',
    stopped: '✅ Task stopped',
    cancelFailed: 'Cancel failed (agent may be idle)',
  },
  index: {
    questionsNotReady: 'Question service not ready',
  },
  // 远程提问桥（questions/router.mjs）——question cards, numbered replies, receipts, escalation
  questions: {
    cardTitle: (text) => `Question: ${text}`,
    noContextPrompt: 'The agent needs you to make a choice',
    multiSelectTag: '(multi-select)',
    singleSelectTag: '(single-select)',
    replyNumberHint: 'Reply with option numbers',
    replyNumberHintMulti: 'Reply with option numbers (multi-select: comma-separated, e.g. 1,3)',
    replyNumberSuffix: (how) => `(${how})`,
    answeredOrExpired: 'This question was already answered or has expired',
    alreadyAnsweredFirstWin: 'This question was already answered (first answer wins)',
    rejectedExpiredOrInvalid: (expired) => `Answer rejected (${expired ? 'expired' : 'verification failed'})`,
    rejectedMismatch: 'Answer rejected (question mismatch)',
    goOriginalChat: 'Please go back to the original conversation',
    // keeps the 答： protocol keyword: the reply matcher in router.mjs only accepts /^答[:：]/
    customAnswerHint: '✍️ Custom answer: reply directly with 「答：<your answer>」',
    skippedFeedback: '⏭ Skipped this question: returned to desktop',
    invalidOption: 'Invalid option (only the numbers given with the question are accepted)',
    answeredWithLabels: (labels) => `✅ Answered: ${labels.join(', ')}`,
    answerTooLong: (max) => `Answer too long (over ${max} characters), rejected; please shorten and resend, or answer directly on the desktop`,
    answeredCustom: (text) => `✅ Answered (custom): ${text}`,
    emptyCustomAnswer: 'Please write your answer after 「答：」',
    noChatContextHint: 'This reply could not be matched to a question card (missing conversation context); go back to the original card or settle it in the admin console',
    notAuthorizedToAnswer: 'This question is not yours to answer (not authorized)',
    singleOnlyHint: 'This is a single-select question; reply with one number only',
    outOfRangeHint: (max, multi) => `Number must be between 1-${max}${multi ? '; separate multiple choices with commas (e.g. 1,3)' : ''}`,
    wrongNumberEcho: (why, hint) => `❓ ${why}\n${hint}`,
    escalationText: (question, note, waited) => `Question still awaiting an answer: ${question}\n${note} (waited ${waited}s). Tap the buttons on the option card to answer; channels without a card can reply with the option numbers.`,
    escalationWaitingFallback: 'still waiting for an answer',
    escStageNote1: 'Question still awaiting an answer',
    escStageNote2: 'Question still awaiting an answer (2nd reminder)',
    terminatedText: '⏹ Terminated: the agent session has ended, question cancelled',
    skippedResolvedText: '⏭ Skipped: returned to desktop',
    timeoutResolvedText: '⏱ Timed out without an answer: returned to desktop (buttons disabled)',
    answeredWithLabelsVia: (labels, via) => `✅ Answered: ${labels.join(', ')} (via ${via})`,
  },
  // 裁决失败话术（inbound/verdict-text.mjs）
  verdict: {
    nounApproval: 'This approval',
    nounQuestion: 'This question',
    tokenRequired: 'This action is missing a valid credential; go back to the conversation where it started and click again',
    keyMismatch: 'The action does not match its target; use the original card',
    sourceChatMismatch: 'Please go back to the original conversation',
    alreadyResolved: (noun) => `${noun} was already handled; no need to repeat`,
    expired: (noun) => `${noun} has expired; please start again`,
    invalidDecision: 'Invalid action type',
    notFound: (noun) => `${noun} was already handled or has expired`,
    cardMissing: 'The original message may have been deleted, so the result cannot be shown here; the ledger is authoritative',
  },
  // 命令族与远程对话回执（inbound/conversation.mjs）
  conversation: {
    helpLines: [
      'Commands:',
      '  /status — View bindings and agent status',
      '  /agent — Grouped active sessions view (workspace | sid | status | outbound channels | quiet)',
      '  /agent use <workspace|sid prefix> — Switch this chat to that session (smart bind)',
      '  /agent back — Unbind this chat, back to channel default',
      '  /tasks — List active tasks (taskRef | workspace | status | attention)',
      '  /use <workspace|sid prefix> — Select a task (same as /agent use; delivers the original message when a selection card is shown)',
      '  /bind <sessionId> — Bind to a specific session (exact sid-level bind)',
      '  /unbind — Unbind (back to channel default routing: channel default agent, else most recent)',
      '  /stop — Cancel the current turn',
      '  /route — Show current two-way resolution (session→channel / channel→session)',
      '  /quiet <workspace|sid> — Silence outbound pushes for that session (remote chat unaffected)',
      '  /unquiet <workspace|sid> — Resume outbound pushes for that session',
      '  /help — This help',
      '',
      'Plain text = chat; ! prefix = steer; trailing .. = send immediately (within merge window).',
      'Long tasks heartbeat automatically (default 15 min) with stall warnings (10 min without events by default); tap the button to stop on card channels, otherwise /stop.',
    ],
    statusBindLabel: 'Bind: ',
    bindUnset: '(not explicitly bound: channel default routing)',
    statusTargetLabel: 'Target: ',
    targetUnset: '(no active session; /bind first or wait for an agent to start)',
    statusStateLabel: 'Status: ',
    statusNotFound: 'not found',
    activeSessionsLabel: 'Active sessions: ',
    activeSessionsNone: '(none)',
    bindUsage: 'Usage: /bind <sessionId> (use /status to list active sessions first)',
    bindMissingSession: (target) => `Session ${target} does not exist (use /status to list active sessions)`,
    boundReceipt: (target) => `Bound to ${target}`,
    unboundReceipt: 'Unbound (back to channel default routing)',
    stopNone: 'No session available to stop',
    stopRequested: (sid) => `Cancellation requested for ${sid}'s current turn`,
    stopFailed: 'Cancel failed (the agent may already be idle)',
    agentUsage: 'Usage: /agent (active session list) | /agent use <workspace|sid prefix> | /agent back',
    routeUnavailable: 'Routing engine not wired (v0.3.2 router missing): /route unavailable; /status still shows sessions and bindings.',
    quietUnavailable: 'Routing engine not wired (v0.3.2 router missing): /quiet unavailable; /status still shows sessions and bindings.',
    quietUsage: (cmd) => `Usage: /${cmd} <workspace name | sessionId | sid prefix (>=4 chars)>`,
    quietWriteFailed: (cmd) => `/${cmd} write failed (routing state store unavailable), please retry later`,
    quietMarkMuted: '🔇 Muted',
    quietMarkResumed: '🔔 Resumed',
    quietReceipt: (mark, label, sid, matchedBy) => `${mark} outbound pushes for ${label} / ${sid} (${matchedBy})`,
    quietHint: '(remote approvals and conversation unaffected; /unquiet <workspace|sid> to resume)',
    unknownWorkspace: '(unknown workspace)',
    unknownCommand: (cmd) => `Unrecognized command /${cmd} (see /help for the command list)`,
    agentListUnavailable: 'Routing engine not wired (v0.3.2 router missing): /agent list unavailable; /status still shows sessions and bindings.',
    agentListHeader: 'Active sessions grouped view (workspace | sid | status | outbound channels | quiet):',
    agentListDegraded: '(session registry not wired: falling back to host agent list, activity ordering unavailable)',
    agentListEmpty: '  (no active sessions: start one on the host, or /bind <sessionId>)',
    statusUnknown: 'unknown',
    outboundUnavailable: '(resolution unavailable)',
    agentListFooter: '(/agent use <workspace|sid prefix> to switch; /agent back for channel default; /route for two-way resolution)',
    matchedByWorkspace: (needle) => `workspace=${needle}`,
    matchedBySessionId: 'sessionId exact match',
    matchedBySidPrefix: 'unique sid prefix match',
    prefixAmbiguous: (needle, count) => `Prefix ${needle} matched ${count} active sessions, please specify exactly:`,
    prefixHint: '(or match exactly by workspace name)',
    noMatch: (needle) => `No session matched ${needle} (use /agent to list active sessions; sid prefix matching needs at least 4 chars)`,
    agentUseUsage: 'Usage: /agent use <workspace name | sessionId | sid prefix (>=4 chars)>',
    agentUseBound: (workspace, sid, matchedBy) => `Bound to ${workspace} / ${sid} (${matchedBy}; /agent back for channel default)`,
    agentBackBound: (sid) => `Back to channel default (unbound from ${sid})`,
    agentBackUnbound: 'No explicit binding (already on channel default routing)',
    routeOutboundHeader: '[Outbound] Current session → channels (layered resolution)',
    routeNoTarget: '  No target session (no binding and no active session to fall back on)',
    routeInboundHeader: '[Inbound] This channel → session (current resolution)',
    routeSourceLine: (label) => `  Source: ${label}`,
    routeTargetLine: (sid) => `  Target: ${sid ?? '(none)'}`,
    routeAmbiguousLine: (ambiguous) => `  Ambiguous: ${ambiguous ? 'yes (multiple active sessions, delivered to most recent)' : 'no'}`,
    routeCandidatesLine: (joined) => `  Candidates: ${joined}`,
    routeChannelDefaultLine: (channel, value) => `  Channel default agent (${channel}): ${value ?? 'not configured'}`,
    noActiveSession: 'No active session to deliver to (bind with /bind <sessionId>, or check /status)',
    sessionGone: (sid) => `Session ${sid} does not exist or has exited (check /status)`,
    deliverFailed: 'Delivery failed (see host logs)',
    deliveredAmbiguous: (sid, count) => `Delivered to ${sid} (that workspace has ${count} active sessions; use /agent use or /bind to target one)`,
    groupControlDenied: 'Remote control is not allowed in group chats; please use the original private chat',
    controlSourceUnverified: 'Remote control source cannot be verified; please use the original private chat',
    conversationDisabled: 'Remote conversation is disabled by default; enable it explicitly in session policy',
    notPaired: 'Please complete pairing before operating',
    controlRejected: 'Remote control rejected; please confirm on the desktop',
    joiner: ', ',
    // /route inbound-source labels (mirroring agent-router source values)
    inboundSourceLabels: {
      bind: 'explicit binding (/bind or /agent use)',
      'channel-default': 'channel default agent',
      'single-agent': 'single-agent fallback',
      latest: 'most recent activity (default fallback)',
    },
  },
  // 晨报（ledger.mjs composeDigest + index.mjs 标题）
  digest: {
    title: '📊 Notification digest',
    windowLine: (from, to, total) => `Window: ${from} ~ ${to}, ${total} notifications`,
    completed: (n) => `✅ completed x${n}`,
    error: (n) => `❌ error x${n}`,
    agentError: (n) => `❌ agent error x${n}`,
    blocked: (n) => `🚫 blocked x${n}`,
    aborted: (n) => `⏹ aborted x${n}`,
    maxTokens: (n) => `⚠️ token cap x${n}`,
    interrupted: (n) => `⏸ interrupted x${n}`,
    approval: (n) => `🔐 approval x${n}`,
    other: (n) => `other x${n}`,
    joiner: ', ',
    failedLine: (n) => `${n} deliveries failed (see logs)`,
    empty: (from, to) => `Window: ${from} ~ ${to}, no notifications`,
  },

  // 白名单拒绝回执 + decide 来源校验话术（inbound/bus.mjs）
  bus: {
    identityLine: (channelName, userId) => `Your ${channelName} identity is ${userId}.`,
    guidedReply: (idLine) => `${idLine}\nGuided mode is active (whitelist is empty). Send /pair <pairing code> to bind (the first binder becomes owner); the code is in the host startup log. /whoami shows your identity.`,
    whitelistReply: (idLine) => `${idLine}\nYou are not on the whitelist. Ask an admin to generate a pairing code, then send /pair <pairing code> to bind.`,
  },

  // 渠道适配器回执（telegram-bot.mjs）
  telegram: {
    terminalFallbackSuffix: '(buttons invalidated)',
    truncateMark: '…(content too long, truncated)',
    refExpired: 'This action was already handled or has expired (buttons are single-use)',
    sourceNote: (user) => `(via telegram user ${user})`,
    answeredShort: '✅ Answered',
    approvedOnce: '✅ Approved (single use)',
    rejected: '❌ Rejected',
    approveButton: '✅ Approve (this call)',
    rejectButton: '❌ Reject',
    customAnswerButton: '✍️ Custom answer',
    skipButton: '⏭ Skip',
    editFallbackNote: '(action completed; the original message may have been deleted)',
  },
  // 渠道适配器回执（feishu-bot.mjs）
  feishu: {
    approveButton: '✅ Approve (this call)',
    rejectButton: '❌ Reject',
    approvalResolvedTitle: 'Approval completed',
    actionResolvedTitle: 'Action completed',
    questionResolvedTitle: 'Question answered',
    unsupportedMessageType: 'This message type is not supported yet',
    cardExpiredToast: 'This action was already handled or has expired (please handle it on the desktop)',
    unknownAction: 'Unknown action',
    answeredShort: '✅ Answered',
    approvedOnce: '✅ Approved (single use)',
    rejected: '❌ Rejected',
    sourceNote: (user) => `(via Feishu user ${user})`,
    groupDowngradeNote: '(group chat downgraded to plain text; please use a private chat)',
    cardPatchFailedNote: '(the original card can no longer be edited; this is the authoritative result)',
  },
  // QQ 网关卡片/按钮回执（qq-gw.mjs）
  qq: {
    approveLabel: '✅ Approve',
    approveVisited: 'Approved',
    rejectLabel: '❌ Reject',
    rejectVisited: 'Rejected',
    selectedVisited: 'Selected',
    markdownFooter: (isUserTarget) => `Tap a button to decide${isUserTarget ? ' (only you can tap)' : ''}:`,
    customAnswerLabel: '✍️ Custom answer',
    resultLine: (text) => `[Approval result] ${text}`,
  },
  // 钉钉审批文本回执（dingtalk-stream.mjs）
  dingtalk: { resultLine: (text) => `[Approval result] ${text}` },
  // WxPusher 审批文本回执（wxpusher-callback.mjs）
  wxpusher: { resultLine: (text) => `[Approval result] ${text}` },

  // 渠道自检（health.mjs / notify_test tool push）
  health: {
    title: 'dsh-notifier self-check',
    testMessage: 'dsh-notifier channel self-check: if you receive this, the channel is configured correctly.',
  },
}

const TABLE = { zh: ZH, en: EN }

/** 按语言取文案表；未知/缺失回落 zh。own-property 校验：避免 `__proto__`/`constructor`
 *  等继承键命中 TABLE 原型链（CodeRabbit：返回非表对象会让格式化侧读出 undefined）。 */
export function stringsOf(lang) {
  return Object.prototype.hasOwnProperty.call(TABLE, lang) ? TABLE[lang] : ZH
}
